modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="macrokeybinds" #mandatory
version="${file.jarVersion}" #mandatory
displayName="MacroKeybinds Mod" #mandatory
description='''''' #mandatory
displayURL="https://discord.gg/xTqj3ZSeH4"
credits="All credits for Thomas7520"
authors="Thomas7520"

