modLoader="javafml" #mandatory
loaderVersion="[45,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="macrokeybinds" #mandatory
version="${file.jarVersion}" #mandatory
displayName="MacroKeybinds" #mandatory
description='''MacroKeybinds is a mod that allows the user to create macros in order to execute a task faster.''' #mandatory
displayURL="https://discord.gg/xTqj3ZSeH4"
credits="All credits for Thomas7520"
authors="Thomas7520"

